### ISSUE TITLE
CHARTS: Enhancement: Reconsider dot-scaling of the legend in 'global_comparison.png'

### ISSUE THREAD

**Issue by bechandcock** [The-Academic-Observatory/observatory-platform#120]
When the Charting Library creates 'global_comparison.png' (e.g. when making an Institutions report), the legend for the sizes of the dots shows as a range of black dots which do not scale well with the figure. Consider whether a more dynamic sizing would suit this chat better.

**Comment by bechandcock** [comment]
I am assigning this to @cameronneylon to confirm closing this issue for being addressed by the recent re-design of that code.

**Comment by cameronneylon** [comment]
Superseded and issue largely resolved with move to plotly
