### ISSUE TITLE
Add additional comments to Charting Library: defaults.py

### ISSUE THREAD

**Issue by bechandcock** [The-Academic-Observatory/observatory-platform#128]
Add inline comments to all defaults explaining what they are

~academic_observatory/analysis/defaults.py

**Comment by bechandcock** [comment]
I am assigning this to @cameronneylon to confirm closing this issue for being addressed by the recent re-design of that code.

**Comment by cameronneylon** [comment]
This has not been done but a thorough refactor is required along with better documentation so will close this version
