### ISSUE TITLE
REPORTS: license for precipy missing

### ISSUE THREAD

**Issue by rhosking** [The-Academic-Observatory/observatory-platform#138]
Should be a simple fix, something to reach out to Ana about

**Comment by rhosking** [comment]
@jdddog does the license checker use metadata from PyPi for license checks, or the codebase itself. Precipy now has a license file included, but no corresponding metadata in Pypi, so was just wondering if this issue can be closed

**Comment by jdddog** [comment]
AFAIK it checks the license given in setup.py, e.g. https://github.com/The-Academic-Observatory/observatory-platform/blob/develop/setup.py#L27, but we can close it because we added an exception to the license checker for this package anyway.
