### ISSUE TITLE
Update contributing instructions on CONTRIBUTING.md’

### ISSUE THREAD

**Issue by bechandcock** [The-Academic-Observatory/observatory-platform#150]
Adding this as an issue to make sure it doesn’t get lost on Slack and other discussions.

The instructions on ‘CONTRIBUTING.md’ need to be updated. In their current form they are only helpful if one already knew which steps match with which phases, in which case one would not need to read instructions :-)

The section ‘**Developing a feature**’ is helpful, but the steps that follow in '**Detailed instructions on how to use Git ... '** do not match up in the numbering in ‘**Developing a feature’**. This makes it unclear which steps should be done prior to developing code, and which match up with updating the Academic Observatory with the code that you have developed.

Could the section starting '**Detailed instructions on how to use Git ... '** be re-numbered or divided into sections to match the three phases noted in ‘‘**Developing a feature**’? Or maybe some sub headings?

**Comment by jdddog** [comment]
Thanks Rebecca, I'll have a look at this one this week
