### ISSUE TITLE
CHARTS: Allow for a year_range rather than requiring a single focus_year for most graphs

### ISSUE THREAD

**Issue by cameronneylon** [The-Academic-Observatory/observatory-platform#151]
Currently most charts either have a year_range or a focus_year. This is mutually exclusive and so graphs are either plot change over time or focus on a single year. There are a few exceptions to this (eg ScatterPlot which has a filter function) but how this is implemented is inconsistent.

*Proposal:* All charts should accept a year_range parameter which can be a single an int for a single year, a tuple (containing start and end years passed to `range`) or a list of years. This should be handled cleanly so that the correct data is then selected. This will require some aggregation for some graphs where multiple years are requested.

**Comment by bechandcock** [comment]
I am assigning this to @cameronneylon to confirm closing this issue for being addressed by the recent re-design of that code.

**Comment by cameronneylon** [comment]
Not done in this way but superseded by other work therefore closing
