### ISSUE TITLE
Rename Master Branches Across Repos

### ISSUE THREAD

**Issue by cameronneylon** [The-Academic-Observatory/observatory-platform#181]
The issue of the naming of the "master" branch has been brought up as an issue in a number of settings. It's not clear to me whether Github is currently supporting renaming to something less toxic (like "main") whereas there are some discussions in the git project and related efforts to look at the default name of the initialised branch.

Worth looking into what our options are here because it will flow through into documentation and processes presumably. Will be something we should consider as we move towards opening the repos in general.

**Comment by jdddog** [comment]
I have renamed the master branch to main, as this is a supported feature in Github now: https://github.com/github/renaming#renaming-existing-branches

Please update your local environments with the following instructions:
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
```
