### ISSUE TITLE
Keeping track of required system packages per individual DAG

### ISSUE THREAD

**Issue by aroelo** [The-Academic-Observatory/observatory-platform#225]
See https://github.com/The-Academic-Observatory/observatory-platform/pull/206#discussion_r457037785
Currently the Dockerfile that is used to build the airflow container installs a number of packages: git, build-essential, pigz, mawk

Some of these are necessary project-wide (e.g. to install 'observatory platform': git, build-essential) and some are related to specific tasks inside DAGs/telescopes.

With a growing number of DAGs, it might be a good idea to keep track of which package is related to which DAG/task.

1.  One simple way would be to do this manually, in the way of adding comments, referring to the DAG and task id. E.g. the install command could be:
```
RUN apt-get update -yqq && apt-get install -y \
    git \ 
    build-essential \
    pigz \ # crossref_metadata.extract, another_dag.task
    mawk # crossref_metadata.transform
```

2. Another way would be to use a tailored image for the tasks that require additional system packages. The image can then be used with either a DockerOperator or KubernetesPodOperator. I'm not sure if this is the best idea, we might end up with a large number of images and I think all of them should include the base image of the observatory platform (?) I wanted to mention the possibility though.

3. Any other ideas @rhosking, @jdddog

**Comment by jdddog** [comment]
Adding comments to the Dockerfile would be good for now

**Comment by jdddog** [comment]
@aroelo can we close this one? Perhaps we could write this in a section in the contributing guide for writing a telescope?
