### ISSUE TITLE
Data QA: Create QA table for Unpaywall

### ISSUE THREAD

**Issue by rhosking** [The-Academic-Observatory/observatory-platform#229]
The main deliverable of this task is a SQL query, which can be in BigQuery that produces a set of useful information for better understanding a unpaywall release. It will look at one unpaywall release at a time (changing the FROM part of the query to query another release)

Later phases of this work would be to automate the running of this (and other queries) through airflow, but this is not in scope for now. This can can likely be developed using the BigQuery Web UI.

I suggest making use of nested fields in BigQuery to organise the results of the query (counts, distributions, etc could be examples of types of metrics you want to capture). We are interested in grouping features of the dataset into both yearly metrics, and a whole of dataset metrics. 

This work will be highly iterative, with the idea of slowly expanding the scope of what is being determined. The initial goal is to get a preliminary set of metrics being returned, and a query structure that can be extended to add further metrics in over time.

**Comment by bechandcock** [comment]
I am assigning this to @tuanchien to address or close as I moved on to other projects.

**Comment by rhosking** [comment]
Fair enough, though looking over the description, I think this work has been subsumed by other approaches and in any case needs rethinking before writing up another issues. So closing this for now
