### ISSUE TITLE
Telescope workflow implementation: ORCID

### ISSUE THREAD

**Issue by aroelo** [The-Academic-Observatory/observatory-platform#233]
**Name**: ORCID
**Harvest Type**: Snapshot/API
**Snapshot Frequency**: Yearly (?)

A public data file is published yearly which contains a snapshot of all public data in the ORCID Registry associated with an ORCID record that was created or claimed by an individual up until that date, see https://support.orcid.org/hc/en-us/articles/360006897394-How-do-I-get-the-public-data-file-#01 and https://orcid.figshare.com/. 

> The file contains the public information associated with each user's ORCID record. Each record is included as a separate file in both JSON and XML in the 2013-2017 files. In the 2018 file, each record is included as a separate file in XML, and each full activity section for each record is included as a separate file in XML. For those who prefer JSON, use the [ORCID Conversion Library](https://github.com/ORCID/orcid-conversion-lib) to convert the XML files to JSON.

As an ORCID member (which I don't think we are?) you receive credentials to access their Amazon S3 ORCID data sync repository any time and create a snapshot.

They also have the ORCID public API which we could maybe use to get all records see e.g. https://members.orcid.org/api/tutorial/search-orcid-registry.

@rhosking would a yearly update be sufficient or would it be worthwhile to explore options to get updates more frequently?

**Comment by aroelo** [comment]
After inspecting the data a bit more it seems there are a couple of categories for each ORCID id; works, employments, eductions.
Would we like one table with a row per ORCID id and columns for each of these categories, or split these categories up into different tables? They are stored in separate files as such:
![image](https://user-images.githubusercontent.com/22207600/90101396-31840500-dd71-11ea-82ce-244b1711a388.png)

Where e.g. '0000-0003-0776-6060' is the id of a single individual

**Comment by rhosking** [comment]
Thanks @aroelo as we discussed, I am working towards getting us credentials to access the Data Sync service.

I don't have an immediate preference on the data organisation, do you have any links to the schemas that I can take a look over? Do they have a python library for turning the XML to JSON if I remember?

**Comment by aroelo** [comment]
They have a Java conversion tool. I had a quick look whether they have some kind of python library to convert the file, but couldn't find one.

I found that using the `xmltodict` python package works quite well, tried this out with one xml file.
[0000-0003-0776-6060_works_28415306.xml.zip](https://github.com/The-Academic-Observatory/observatory-platform/files/5067887/0000-0003-0776-6060_works_28415306.xml.zip)

```
orcid_file_path = "/Users/284060a/Downloads/0/060/0000-0003-0776-6060/works/0000-0003-0776-6060_works_28415306.xml"

with open(orcid_file_path, 'r') as f:
    xml_dict = xmltodict.parse(f.read())
    with open('~/orcid_json_out.json', 'w') as json_out:
        with jsonlines.Writer(json_out) as writer:
            writer.write_all([xml_dict])

```

I uploaded the result into bigquery (replacing some illegal characters) and the schema looks something like this:
<details>

```
[
  {
    "fields": [
      {
        "mode": "NULLABLE",
        "name": "common_url",
        "type": "STRING"
      },
      {
        "fields": [
          {
            "mode": "NULLABLE",
            "name": "common_year",
            "type": "INTEGER"
          }
        ],
        "mode": "NULLABLE",
        "name": "common_publication_date",
        "type": "RECORD"
      },
      {
        "mode": "NULLABLE",
        "name": "work_type",
        "type": "STRING"
      },
      {
        "fields": [
          {
            "mode": "NULLABLE",
            "name": "work_citation_value",
            "type": "STRING"
          },
          {
            "mode": "NULLABLE",
            "name": "work_citation_type",
            "type": "STRING"
          }
        ],
        "mode": "NULLABLE",
        "name": "work_citation",
        "type": "RECORD"
      },
      {
        "fields": [
          {
            "fields": [
              {
                "mode": "NULLABLE",
                "name": "common_external_id_relationship",
                "type": "STRING"
              },
              {
                "fields": [
                  {
                    "mode": "NULLABLE",
                    "name": "_text",
                    "type": "STRING"
                  },
                  {
                    "mode": "NULLABLE",
                    "name": "transient",
                    "type": "BOOLEAN"
                  }
                ],
                "mode": "NULLABLE",
                "name": "common_external_id_normalized",
                "type": "RECORD"
              },
              {
                "mode": "NULLABLE",
                "name": "common_external_id_value",
                "type": "STRING"
              },
              {
                "mode": "NULLABLE",
                "name": "common_external_id_type",
                "type": "STRING"
              }
            ],
            "mode": "REPEATED",
            "name": "common_external_id",
            "type": "RECORD"
          }
        ],
        "mode": "NULLABLE",
        "name": "common_external_ids",
        "type": "RECORD"
      },
      {
        "mode": "NULLABLE",
        "name": "work_journal_title",
        "type": "STRING"
      },
      {
        "fields": [
          {
            "mode": "NULLABLE",
            "name": "common_title",
            "type": "STRING"
          }
        ],
        "mode": "NULLABLE",
        "name": "work_title",
        "type": "RECORD"
      },
      {
        "fields": [
          {
            "mode": "NULLABLE",
            "name": "common_source_name",
            "type": "STRING"
          },
          {
            "fields": [
              {
                "mode": "NULLABLE",
                "name": "common_host",
                "type": "STRING"
              },
              {
                "mode": "NULLABLE",
                "name": "common_path",
                "type": "STRING"
              },
              {
                "mode": "NULLABLE",
                "name": "common_uri",
                "type": "STRING"
              }
            ],
            "mode": "NULLABLE",
            "name": "common_source_orcid",
            "type": "RECORD"
          }
        ],
        "mode": "NULLABLE",
        "name": "common_source",
        "type": "RECORD"
      },
      {
        "mode": "NULLABLE",
        "name": "common_created_date",
        "type": "STRING"
      },
      {
        "fields": [
          {
            "fields": [
              {
                "mode": "NULLABLE",
                "name": "work_credit_name",
                "type": "STRING"
              }
            ],
            "mode": "REPEATED",
            "name": "work_contributor",
            "type": "RECORD"
          }
        ],
        "mode": "NULLABLE",
        "name": "work_contributors",
        "type": "RECORD"
      },
      {
        "mode": "NULLABLE",
        "name": "visibility",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "put_code",
        "type": "INTEGER"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_peer_review",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_preferences",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_external_identifier",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_keyword",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_funding",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_record",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_qualification",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_bulk",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_distinction",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_research_resource",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_education",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_activities",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_person",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_other_name",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_service",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "path",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_internal",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_work",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_personal_details",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_employment",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_researcher_url",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_deprecated",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "common_last_modified_date",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_history",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_error",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_common",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_invited_position",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_membership",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_email",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "xmlns_address",
        "type": "STRING"
      }
    ],
    "mode": "NULLABLE",
    "name": "work_work",
    "type": "RECORD"
  }
]
```

</details>

I think we might want to drop the columns starting with 'xmlns'

**Comment by rhosking** [comment]
Ah cool, will take a better read through that on Monday. I'm leaning towards three separate tables though, purely because ORCID has already made that decision to split the records and it would take code (transformation) to join them back together, which is against one of the telescope principles. We can run a SQL query to join them in a derived table I am presuming without too much trouble. But if there is another compelling reason to join them before saving into a single table, then I'm all ears

**Comment by aroelo** [comment]
The file hierarchy related to the screenshot above is as follows:
[checksum]/[3 digits checksum]/[iD]/[activity type]/[iD]_[activity_type]_[putcode].xml

Initially I thought it would make sense to have each 'put_code' be a separate entry/row. Each individual file represents a unique put_code.

> Put code
> Each item in the ORCID iD is assigned a put code which uniquely identifies it. When reading an entire record or section, the put code can be found as an attribute of the item. When calling a specific item on a record, the put code is used to identify the item. Put codes are unique within the type of item they refer to. Using this example, only one work in the ORCID Registry will have the put code 733535, though 733535 may also used as a put code for a funding item or a keyword.

However, the Lambda File keeps track of when each ORCID **record** is last modified, so it doesn't 
use the ORCID put_code. The record (or iD in the file hierarchy) is at the level of an individual. This made me think that maybe it makes more sense to have each record be a seperate entry/row and have nested rows for the different put_code entries.

I guess this is also related to whether we will have the three seperate tables for works/educations/employments.

@rhosking what do you think?

**Comment by rhosking** [comment]
Is it that new items or changes are always put into a new put_code/file, or am I miss-understanding how it works? If we could keep track of which put codes (unique to each ORCID ID) we have already seen, can we use the last modified code to then figure out what put_codes are new?

Additionally, it might be possible just by using the transfer service to identify which files have been changed

I'm still happy with three separate tables, joining these up when required is straightforward enough. Is there an additional table/dataset that just has ORCID record details, such as their name etc? or is this information contained within the works/education/employment?

**Comment by rhosking** [comment]
Looking at the documentation, are 'Peer review' and 'Funding' different categories/files?

**Comment by aroelo** [comment]
> Is it that new items or changes are always put into a new put_code/file, or am I miss-understanding how it works? If we could keep track of which put codes (unique to each ORCID ID) we have already seen, can we use the last modified code to then figure out what put_codes are new?

How they describe it I assume that new items or changes are indeed always in a new put_code/file, will check to be sure. We could look at the existing table to check which put codes already exist. This also depends on how we'll handle duplicate rows in general with BigQuery. If we overwrite them we could just simply add all put_codes from the modified record.

It's definitely possible, I just thought maybe I misinterpreted on which level we should be working, either iD or put_code.

> Additionally, it might be possible just by using the transfer service to identify which files have been changed

I will look into this more today, now that we have the credentials.

> I'm still happy with three separate tables, joining these up when required is straightforward enough. Is there an additional table/dataset that just has ORCID record details, such as their name etc? or is this information contained within the works/education/employment?

I find it a bit confusing, but I don't think they are in the 'ORCID Public Data File' as these seem to only contain the activities. So I think we would have to use the API separately for this. Looking into it now.

> Looking at the documentation, are 'Peer review' and 'Funding' different categories/files?

Ah yep, sorry I missed those in the subset. So there are 5 'activities', and I guess we would have 5 different tables then.
1.  Education
2.  Employment
3.  Funding
4.  Peer review
5.  Works

**Comment by aroelo** [comment]
@rhosking Just got back a response from Melroy:
Comparing summary vs individual activity files, using the xsd schema's that can be found here: https://github.com/ORCID/orcid-model/tree/master/src/main/resources/record_3.0.

Extra fields in individual activity file per activity:
**Education**
None

**Employment**
None 

**Funding** 
- organization-defined-type
- short-description
- amount
- contributors 
Container for the contributors of a funding.

**Peer review**

- review-identifiers 
Unique identifier(s) of the review. <i>This identifier refers to the review itself, NOT to the item that was reviewed.</i> At least one identifier is required. In the case where there is no persistent unique identifier for the review, the source providing the data should generate a locally-sourced unique identifier for the review (e.g., type "organization-defined-type"). This field will be checked when adding new reviews to prevent double counting of review activity. Identifier types must be selected from the list at https://pub.orcid.org/v2.0/identifiers
- review-completion-date 
The date on which the review was completed. Allowable values: yyyy; yyyy-mm; yyyy-mm-dd, formatted using the ORCID fuzzy date format.
- subject-external-identifier 
The unique identifier of the subject being reviewed. Identifier types must be selected from the list at https://pub.orcid.org/v2.0/identifiers
- subject-container-name
The name of the journal, conference, grant review panel, or other applicable object of which the review subject was a part.
-subject-type
The type of object that the review subject is (for example, a journal article, grant, etc).
- subject-name
The name/title of the object that was reviewed.
- subject-url
The URL of the object that was reviewed.

**Work**
- short-description 
- citation 
Element containing the type and content of the citation for this work
- contributors 
Container for the contributors of a Work.
- common:language-code 
The language used for the metadata provided about the work
- common:country

**Comment by aroelo** [comment]
@jdddog, @rhosking I'm looking into the google cloud transfer job to sync data from the aws bucket to a google cloud bucket.

It seems that you can't specify a path in the google cloud bucket (https://cloud.google.com/storage-transfer/docs/create-manage-transfer-console#select). I would be transferring single ORCID record files, so it will get quite messy if these are just dumped in our 'download bucket' that is used for all telescopes.

Should I create a separate bucket for this?

**Comment by jdddog** [comment]
That's a bit silly that you can't specify a destination path aye. To work around that with MAG I put the files on a path on the Azure container, that matched where we wanted them to end up in the Google Cloud storage bucket, before transferring them.

Yeah, if you used the transfer service you would have to transfer them to a new bucket on Google Cloud storage and then copy them to the downloads bucket after that.

**Comment by aroelo** [comment]
Having a separate bucket for ORCID I'm contemplating whether this should be added to our Terraform configuration.

I'm not too keen on adding such telescope-specific settings to our more general Terraform set-up, but not sure what a good approach would be.

The resources that need to be created are:
- The bucket itself
- Permissions so that the transfer service account can read/write to bucket
- Permissions so that Observatory Platform service account can read/write to bucket

We could let users set this up manually, so they would create the bucket and assign the right permissions after our general Terraform configuration. Or maybe we could create a separate Terraform .tf file/module that contains 'telescope' configurations. 

This can then contain configurations of other telescopes that might be required in the future as well. It would make it somewhat easier to use Terraform for this instead of having to look up the correct service accounts that are used by the Observatory Platform.

@jdddog Do you have any thoughts on this?
