### ISSUE TITLE
Structuring telescopes with synced data (ORCID, crossref events, etc..)

### ISSUE THREAD

**Issue by aroelo** [The-Academic-Observatory/observatory-platform#235]
@rhosking @jdddog 
The last couple of days I have been looking into both ORCID and crossref events telescopes. Until now we've dealt with telescopes that give 'snapshot' data, creating a new table per snapshot, but for ORCID/crossref events it might be better to have 1 up-to-date table at all times.

For these telescopes we are able to retrieve which entries have been added/modified on a daily basis. This has the benefit that we don't have to download and transform large batches of data every time the telescope is run. I think it makes sense to then create 1 table that is time-partitioned. However, this brings up some design/technical questions.

- Assuming we append data to an existing BigQuery table, how do we avoid creating duplicate rows when re-running the same DAG (accidentally)?
- Will we create a separate DAG for a first-time run creating a BigQuery table with all data up until that day, compared to a DAG that runs daily? 
For example if we want to update crossref events daily, it would be inefficient to set the start_date to 2017-01-01 and the schedule_interval to '@daily'. The DAG will then have to run many times to catch up. It might make more sense to have a separate DAG (which only differs in start_date/schedule_interval) harvest a big chunk of crossref events first with a schedule_interval of '@once', and from that day onwards run a DAG with the '@daily' schedule_interval.
- If a DAG is run quite frequently (daily) will we still store and upload a relatively small 'downloaded' and 'transformed' file for each run?

In the case of crossref events we can easily keep track of any edited or deleted events. For ORCID this depends a bit on how the data will be structured (see https://github.com/The-Academic-Observatory/observatory-platform/issues/233#issuecomment-674724069). Assuming we're keeping track of any edited and deleted entries for both crossref events and ORCID. 
- Do we add entries describing edited or deleted entries to the same table or create different table(s) for this?
- If we add these entries to the same table: When we have an entry describing the modification of an earlier entry, do we use the timestamp of the original entry or that of the actual entry for partitioning?

**Comment by jdddog** [comment]
> @rhosking @jdddog
> The last couple of days I have been looking into both ORCID and crossref events telescopes. Until now we've dealt with telescopes that give 'snapshot' data, creating a new table per snapshot, but for ORCID/crossref events it might be better to have 1 up-to-date table at all times.
> 
> For these telescopes we are able to retrieve which entries have been added/modified on a daily basis. This has the benefit that we don't have to download and transform large batches of data every time the telescope is run. I think it makes sense to then create 1 table that is time-partitioned. However, this brings up some design/technical questions.

Yeah that makes sense to just have one table that is time partitioned.

> 
> * Assuming we append data to an existing BigQuery table, how do we avoid creating duplicate rows when re-running the same DAG (accidentally)?

That's a good question, I need to think about how we can do this in BigQuery a bit more.

> * Will we create a separate DAG for a first-time run creating a BigQuery table with all data up until that day, compared to a DAG that runs daily?
>   For example if we want to update crossref events daily, it would be inefficient to set the start_date to 2017-01-01 and the schedule_interval to '@daily'. The DAG will then have to run many times to catch up. It might make more sense to have a separate DAG (which only differs in start_date/schedule_interval) harvest a big chunk of crossref events first with a schedule_interval of '@once', and from that day onwards run a DAG with the '@daily' schedule_interval.

Yeah I think that in principle the idea of getting all of the existing data to start with and then collect data for each day after that makes sense. Although, I think that it is best to just create one DAG for each data source to keep it simple. For the first DAG run you could set the until-collected-date to be the end date of the DAG run and then for each DAG run after that set the from-collected-date as well.

I wonder if it is better to use collected date rather than occurred date, because if we query by the occurred date every day, and newer data is added for a date before the current DAG run, then it will never be harvested. https://www.eventdata.crossref.org/guide/service/query-api/

> * If a DAG is run quite frequently (daily) will we still store and upload a relatively small 'downloaded' and 'transformed' file for each run?

Yeah.

> 
> In the case of crossref events we can easily keep track of any edited or deleted events. For ORCID this depends a bit on how the data will be structured (see [#233 (comment)](https://github.com/The-Academic-Observatory/observatory-platform/issues/233#issuecomment-674724069)). Assuming we're keeping track of any edited and deleted entries for both crossref events and ORCID.
> 
> * Do we add entries describing edited or deleted entries to the same table or create different table(s) for this?
> * If we add these entries to the same table: When we have an entry describing the modification of an earlier entry, do we use the timestamp of the original entry or that of the actual entry for partitioning?

That's a good question, I need to think about it a bit more as well. Perhaps we just want all of that data to be in there? Maybe @rhosking has some ideas?

**Comment by rhosking** [comment]
I think if we think about general principles, the raw data we collect include updates, so I think it is valuable to keep a notion of these (deletions and updates include). The rate of updates / changes is actually an interesting measurement in its own right. Analytical/Aggregation workflows can always be written to perform any snapshotting / reconciliation if required.

The rest of the discussion also sounds sensible. It might be worth mapping out some scenarios for how updates can arrive, and what could go wrong (and thus needs taking into account). This will inform the design requirements for what we build more concretely. I think I still don't fully understand the use of put_codes, but on the surface it does feel like they are trying to design a system to cater for sending incremental updates.

**Comment by aroelo** [comment]
@rhosking @jdddog @tuanchien Just tagging everyone again since the question resurfaced during our meeting yesterday.
Assuming we append data to an existing BigQuery table, how do we avoid creating duplicate rows when re-running the same DAG (accidentally)?

Two possible solutions:
(Recap: the table is partitioned on the 'collected-date' field of the events and partitioned by day.)
* Try to prevent duplicates: Add the 'release_date' of when the data is harvested as a field. 

During each DAG run, before uploading data to bigquery, query if rows already exist with a release_date that is the same as the release_date of current DAG run. This query would have to be done for each partition (or one query for all partitions if that's possible). Doing this will prevent duplicate rows from e.g. clearing a DAG run which prompts the tasks to run again.

I think this will work fine as long as we use the same airflow database (which I assume we will). Because data is appended, the DAG catchup is set to False, meaning that the 'release_date' will be different for new runs if all DAG info is lost.

* Delete duplicates: Deduplicate per partition during DAG run, requires one query per partition. 

For our initial 'harvest' from 2017-02-17 until now there will be a lot of partitions, so maybe we can skip the deduplication in this case. 
After this, if the data is harvested weekly we would then have to run 7 queries which seems acceptable, but it seems like more effort than the solution above to eliminate duplicated rows which should only exist in rare cases.

Here's a query to deduplicate per partition:
```sql
MERGE `temp.many_random` t
USING (
  SELECT DISTINCT *
  FROM `temp.many_random`
  WHERE d=<collected_date>
)
ON FALSE
WHEN NOT MATCHED BY SOURCE AND d=<collected_date> THEN DELETE
WHEN NOT MATCHED BY TARGET THEN INSERT ROW
```
from https://stackoverflow.com/questions/57900777/deduplicate-rows-in-a-bigquery-partition/57900778#57900778.
This could be executed from the DAG run using the bigquery client.
