### ISSUE TITLE
Design of Web of Science and Scopus Telescopes

### ISSUE THREAD

**Issue by jdddog** [The-Academic-Observatory/observatory-platform#243]
There is a reasonable amount in common for the Web of Science and Scopus telescopes so I'll describe them in one ticket.

The purpose of the Web of Science and Scopus telescopes is to enable institutions to populate their private institutional repositories with Web of Science and Scopus data alongside other public data sources.

Requirements:
* One DAG for Scopus and one DAG for Web of Science.
* Airflow DAG runs every three months (could be a longer time period if necessary): 
  * No catchup / backfill
  * Should fetch data from the current year back to the year 2000 (configurable via a Python variable in the DAG). 
  * Only fetch data for institutions that have an API token stored as an Airflow Connection.
  * The idea is that every 3 months a particular institution gets a fresh release of it's data. Each time you have to fetch all of the data for a particular institution again, because you can only search based on the institution id and a date, not based on what records were updated. So you can never know if data has changed (e.g. a new record added about a publication in the past, or data updated about a publication in the past) without fetching it all.
* Institution BigQuery table:
   * Create a BigQuery institutions table in `<project_id>.coki.institution`, porting over the table `grid` currently in Firebase. 
   * The schema is detailed below.
* Storing API tokens
  *  Stored as an Airflow Connection, one token for a particular institution.
  *  You can lookup the connection for a particular institution in airflow based on the conn_id, which should be composed with: institution grid id + table_name.
  *  Connection details:
     * conn_id: 
          * For WoS: <grid_id of institution>.wos 
          * For Scopus: <grid_id of institution>.scopus 
     * type: HTTP
     * host:
          * WoS connection: search.webofknowledge.com
          * scopus connection: api.elseiver.com
     * login:
          * WoS connection: the WoS username
          * Scopus connection: N/A
     * password: the token
* BigQuery table and schema
  * Each DAG should save the data in the table: 
          * WoS DAG: `<project_id>.clarivate.wos`
          * Scopus DAG: `<project_id>.elseiver.scopus`
  * The schema for the table is defined in the table below, this is based on the current fields that are being used and some extra fields that are required for partitioning. More should be added (details below).
  * Partitioned on the `release_date` field, which is the start date of the DAG run for harvesting articles.
  * Add additional fields to the schema:
     * WoS: https://clarivate.com/webofsciencegroup/solutions/xml-and-apis/
     * Scopus: https://service.elsevier.com/app/answers/detail/a_id/11236/supporthub/scopus/
* Make a script to parse the raw data dumps to the new table.

### Institutions BigQuery Table Schema
| Field | Type | Existing field name | Notes / example |
| -------- | -------- | -------- | -------- | 
| name     | STRING     | name | e.g. University of Liverpool |
| grid_id     | STRING     | the document key | e.g. grid.10025.36 |
| mag_id     | STRING     | msa | e.g. 146655781 |
| scopus_id     | STRING     | scopus | e.g. 60020661 |
| wos_id     | STRING     | wos | e.g. University of Liverpool |

### Web of Science BigQuery Table Schema
| Field | Type | Field in current BigQuery table clarivate.wos  | Notes  |
| -------- | -------- | -------- | -------- |
| wos_id     | STRING     |    wos_id  |
| doi     | STRING     |   doi or wos_doi   |
| grid_id     | STRING     | grid_id   |
| title     | STRING     | wos_title   |
| abstract     | STRING     | wos_abstract   |
| source     | STRING     | wos_source   |
| conference_id     |   STRING   | wos_conference_id   |
| conference     | STRING     | wos_conference   |
| sort_date     | DATE     | wos_sortdate   |
| fund_ack     | STRING     | wos_fund_ack  |
| keywords     | STRING     |  wos_keywords    |
| issn     | STRING     | wos_issn   |
| eissn     | STRING     | wos_eissn   |
| isbn     | STRING     | wos_isbn   |
| eisbn     | STRING     | wos_eisbn    |
| art_no     | STRING     |   wos_art_no   |
| meeting_abs     | STRING     |  wos_meeting_abs    |
| xref_doi     | STRING     |  wos_xref_doi    |
| parent_book_doi     | STRING     |  wos_parent_book_doi    |
| harvest_datetime     | DATETIME     |   first_lookup  | The datetime that the record was harvested |
| release_date     | DATE     |       | The start_date of the DAG run which creates the release for a given period, the table should be partitioned on this field |

### Scopus BigQuery Table Schema
| Field | Type | Field in current table | Notes |
| -------- | -------- | -------- | -------- |
| scopus_id     | STRING     |   scopus_identifier   | |
| doi     | STRING     |   doi or scopus_doi   | |
| grid_id     | STRING     | grid_id   | |
| title     | STRING     |   doi or scopus_doi   | |
| publication_name     | STRING     |   scopus_publicationName   | |
| cover_date     | DATE     |   scopus_coverDate   | |
| issn     | STRING     |   scopus_issn   | |
| eissn     | STRING     |   scopus_eIssn   | |
| subtype_description     | STRING     |   scopus_subtypeDescription   | |
| openaccess     | BOOL     |   scopus_openaccess   | Has some weird values, perhaps that is why scopus_openaccessFlag exists?   |
| openaccess_flag     | BOOL     |   scopus_openaccessFlag   | |
| citedby_count     | INT64     |   scopus_citedby_count   | Might also need to be cleaned, has some weird values, e.g. "[{$: 1} {$: 37}]", "[{$: 0} {$: 11}]", "[{$: 28} {$: 15 February 2017}]" etc  |
| harvest_datetime     | DATETIME     |  first_lookup   | The datetime that the record was harvested |
| release_date     | DATE     |       | The start_date of thethe DAG run which creates the release for a given period |

**Comment by tuanchien** [comment]
Implemented by issues #21 and #20
