### ISSUE TITLE
Telescope workflow implementation: UCL Discovery repository

### ISSUE THREAD

**Issue by aroelo** [The-Academic-Observatory/observatory-platform#248]
Details to be updated.

See https://docs.google.com/document/d/14y7lRHYr3MxGzTsiP3j60t7DOJ1tsJLLAMMhQeDHNMA for more info

**Comment by aroelo** [comment]
I first developed a telescope which gets the number of downloads in a given time period for each book in a single request. 
```
https://discovery.ucl.ac.uk/cgi/stats/get?from={start_date}&to={end_date}&set_name=type&set_value=book&irs2report=main&datatype=downloads&top=eprint&view=Table&title_phrase=top_downloads&limit=all&export=CSV
```
This works quite nicely, but I found out that we also need the downloads per country for each book in a time period, and filter on only 'open access' books, not just all books. So we need loop through book ids and get info for an individual book.

To get info on a list of all open access books, there's a couple of ways to export the data, see image:
![image](https://user-images.githubusercontent.com/22207600/105671221-4fa78100-5f1d-11eb-9634-573a49d164b7.png)

I have played around a bit with this and I think the CSV will be the easiest to parse and gives the most info.
The url would look something like this:
```
https://discovery.ucl.ac.uk/cgi/search/archive/advanced/export_discovery_CSV.csv?screen=Search&dataset=archive&_action_export=1&output=CSV'&exp=0|1|-date/creators_name/title|archive|-|primo:primo:ANY:EQ:open|type:type:ANY:EQ:book|-|eprint_status:eprint_status:ANY:EQ:archive|metadata_visibility:metadata_visibility:ANY:EQ:show
```

Currently my questions are:
 * Which columns/fields would be useful to get from this csv file for each individual book? I have added the resulting CSV on the google drive [here](https://drive.google.com/file/d/1_vw9vIK-UrW7qDR0qG48lG6L8ZupMVY5/view?usp=sharing) (github does not accept CSV)
 * Are we sure or can we check that this gives a list of all books that we expect? For example, there are no open access books that are not labeled 'open access' end we'll end up missing those?

**Comment by alkimozaygen** [comment]
Hi Aniek,

- The columns that would be helpful to get from this CSV for the individual title are
eprintid, creators_name.family, creators_name.given, title, ispublished, subjects, divisions, keywords, abstract, date, publisher, official_url, oa_status, language, doi, isbn_13, language_elements, lyricists_name.family, lyricists_name.given, series, pagerange, pages, editors_name.family, editors_name.given

Here we will use eprintid column to get the country stats using

http://discovery.ucl.ac.uk/cgi/stats/get?range=_ALL_&set_value=eprintid&datatype=countries&view=Google%3A%3AGeoChart&date_resolution=month&export=CSV

- UCL Press is a fully open access university press. As far as I know, they never publish non-open access books.  In addition to books hosted in UCL Discovery repository, they have also a few books that are provided only via their digital platform (https://ucldigitalpress.co.uk/), such as 'Books as Open Online Content' and 'Academic Book of the Future'. 
So in addition to the CSV file, those books that are hosted on their digital platform must be added to the title list. Probably we will get this via their ONIX file.

- As long as it is published, we should have it as zero downloads. I guess they would want to learn that their book has zero downloads. It would also show that the book's access data is checked.

**Comment by aroelo** [comment]
> Hi Aniek,
> 
> * The columns that would be helpful to get from this CSV for the individual title are
>   eprintid, creators_name.family, creators_name.given, title, ispublished, subjects, divisions, keywords, abstract, date, publisher, official_url, oa_status, language, doi, isbn_13, language_elements, lyricists_name.family, lyricists_name.given, series, pagerange, pages, editors_name.family, editors_name.given

Thanks, I'll have a look at these in a bit and let you know if they raise any other questions.

> * UCL Press is a fully open access university press. As far as I know, they never publish non-open access books.  In addition to books hosted in UCL Discovery repository, they have also a few books that are provided only via their digital platform (https://ucldigitalpress.co.uk/), such as 'Books as Open Online Content' and 'Academic Book of the Future'.

I see, so what is the 'Open access' filter necessary for then? You mentioned on Slack that we need to tick that box as well. If I search only on 'Books' it will give 648 results, if I search on 'Books' and 'Open access' it will give 504 results. Are there 144 books that are not open access? How is that possible if they don't publish non-open access book?

>   So in addition to the CSV file, those books that are hosted on their digital platform must be added to the title list. Probably we will get this via their ONIX file.

What is the probably? Do you want me to have a look at this or is this dependent on something else?

**Comment by aroelo** [comment]
@alkimozaygen The latest version of the UCL discovery table is in BigQuery, could you have a look and comment on the schema if there's anything you'd like to change? I'll send the link to the dataset on Slack

**Comment by alkimozaygen** [comment]
@aroelo looks great. Is it possible to include 'eprintid' field? Because the web page URL of the titles are using the eprintid field.

**Comment by aroelo** [comment]
> @aroelo The schema looks great. Is it possible to include 'eprintid' field? Because the web page URL of the titles are using the eprintid field.

Yeah definitely, this is now referred to as the 'book_id', but I can rename it to eprintid if you prefer :-)

**Comment by alkimozaygen** [comment]
That would be great if you can rename it 'eprintid' so that it would be easier to match with the repository metadata. Thank you  Aniek :)

**Comment by alkimozaygen** [comment]
> Aniek: I see, so what is the 'Open access' filter necessary for then? You mentioned on Slack that we need to tick that box as well. If I search only on 'Books' it will give 648 results, if I search on 'Books' and 'Open access' it will give 504 results. Are there 144 books that are not open access? How is that possible if they don't publish non-open access book?

Alkim: The UCL discovery repository is the university's institutional repository. The UCL Press titles (they have only 182 OA books) is just one part of it. The repository has also books from other presses as well (i.e. https://discovery.ucl.ac.uk/id/eprint/10112328/ is from deGruyter). So we will need to use their ONIX file to filter from those 504 books to get only the ones from the UCL Press.

=======

> Alkim: So in addition to the CSV file, those books that are hosted on their digital platform must be added to the title list. Probably we will get this via their ONIX file.
> 
> Aniek: What is the probably? Do you want me to have a look at this or is this dependent on something else?
> 

Alkim: In fact, we will ask them to include the information about those books to their ONIX file. Because the contents of books such as the 'Books as Open Online Content' and the 'Academic Book of the Future' titles are only given via their web page as HTML. Those titles are not printed, and the UCL Press doesn't provide a PDF version of those titles. That's why they don't have on their ONIX feed they sent to repositories and distributors.

**Comment by aroelo** [comment]
> Alkim: The UCL discovery repository is the university's institutional repository. The UCL Press titles (they have only 182 OA books) is just one part of it. The repository has also books from other presses as well (i.e. https://discovery.ucl.ac.uk/id/eprint/10112328/ is from deGruyter). So we will need to use their ONIX file to filter from those 504 books to get only the ones from the UCL Press.

Ah okay, so we only need access statistics on those 182 OA books? We can filter on the 'publisher' field in the CSV file. So far I have been pulling access statistics on all 504 books.

> Alkim: In fact, we will ask them to include the information about those books to their ONIX file. Because the contents of books such as the 'Books as Open Online Content' and the 'Academic Book of the Future' titles are only given via their web page as HTML. Those titles are not printed, and the UCL Press doesn't provide a PDF version of those titles. That's why they don't have on their ONIX feed they sent to repositories and distributors.

So both the book titles and the access statistics on those books are provided through the ONIX feed? This will be part of the 'ONIX' workflow/telescope then if I understand correctly.

**Comment by alkimozaygen** [comment]
> So both the book titles and the access statistics on those books are provided through the ONIX feed? This will be part of the 'ONIX' workflow/telescope then if I understand correctly.

The ONIX feed will provide us title names and their bibliographic data and we will ask publishers to include URLs of the titles' web pages so that we can collect usage data from their web site's Google Analytics. Normally ONIX feed is sent to repositories and book distributors. For example, DOAB's metadata is composed of the bibliographic data that is collected from publishers' ONIX feeds. 

In this project, publishers will send their ONIX feed to our FTP server. Then using those ONIX feeds we will learn their book titles and their bibliographic data. Then using those titles and web URLs, also some title identifiers on repositories, we will collect book usage data from those repositories and Google Analytics.
