### ISSUE TITLE
Telescope workflow implementation: Google Analytics

### ISSUE THREAD

**Issue by aroelo** [The-Academic-Observatory/observatory-platform#249]
Details to be updated.

See https://docs.google.com/document/d/14y7lRHYr3MxGzTsiP3j60t7DOJ1tsJLLAMMhQeDHNMA for more info

**Comment by rhosking** [comment]
Branch for this work, with schema created: https://github.com/The-Academic-Observatory/observatory-platform/tree/feature-google-analytics
