### ISSUE TITLE
Create documentation for dataset: Scopus

### ISSUE THREAD

**Issue by bechandcock** [The-Academic-Observatory/observatory-platform#26]
## Dataset: Scopus
**BigQuery dataset name:** scopus
**BigQuery location:** `academic-observatory-telescope : scopus`
**Category:** raw/original data
**BigQuery key tables:** e.g. scopus_v1
**Dataset description:** Bibliographic and citation data

**Comment by rhosking** [comment]
adding @tuanchien, not a particularly well described issue yet, but a note to document the resulting dataset. This might already have been superseded by more recent issues, if so please close.

**Comment by tuanchien** [comment]
Implemented by #20

**Comment by bechandcock** [comment]
This has changed in what was originally envisioned for these datasets. It now refers to writing the dataset documentation under a Elsevier section in the Datasets section (as different from the Telescopes section). 
https://observatory-platform.readthedocs.io/en/latest/datasets/index.html

**Comment by tuanchien** [comment]
Latest update for #20 changes section heading from scopus to elsevier in 'Datasets' section. Telescope section unchanged.

**Comment by rhosking** [comment]
@tuanchien should this be linked to #269?

**Comment by tuanchien** [comment]
Definitely related to #269 pr and issue #20
