### ISSUE TITLE
Missing fields & data quality of the aggregation workflow output

### ISSUE THREAD

**Issue by jdddog** [The-Academic-Observatory/observatory-platform#272]
The following is a summary of the fields that are missing from the output of the aggregation workflow and some data quality issues that should be explored.

### Missing fields
* Institutions
  * [ ] years.collaborators.<oa, green, gold>
  * [ ] years.diversity.<coki_academic_men_headcount, coki_academic_women_headcount, coki_nonacademic_men_headcount, coki_nonacademic_women_headcount, coki_allroles_women_pc_totalheadcount, coki_academic_women_pc_roleheadcount> 
* Funders
  * [ ] years.institutions.<id, count, name, country, country_code, region, subregion, coordinates, oa, green, gold>
* Publisher
  * [ ] years.institutions.<id, count, name, country, country_code, region, subregion, coordinates, oa, green, gold>

### Data quality
* Funders:
  * It appears that there has been a large decrease in the total number of matches between funders and <institutions, countries, publishers and groups>.
  * Some funders, e.g. Bill and Melinda Gates Foundation, have 200% OA.
* Date ranges:
  * Can the data for the entire dashboard be filtered by by a date range picker where the user can select a start and end date? Like in Kibana. 
  * Are the top level stats (e.g. publications, funders, publishers, events, collaborations) and the non-time based charts and tables (e.g. the open access percentages) calculated based on all time or just between 2000 and 2018? Perhaps these could be calculated dynamically based on a start and end date supplied by the user.

**Comment by cameronneylon** [comment]
Some additional notes from a quick glance I did in funders:

1. Names are almost entirely wrong across the funder table, IDs seems to be correct or at least are in the right country
2. Country codes are inconsistent in case (funders-lower case, institutions-uppercase)
3. Funders table countries seems to be unpopulated, but country code seems to be largely populated

**Comment by cameronneylon** [comment]
Workflow note. We shouldn't use the crossref.published_print date as the main detailed date in the DOI table but the issued date (better to have both really). crossref.published_print is null for a very large proportion of outputs that are never published in print.

Also not sure this is the best place to put these issues as they arise but it seemed like a sensible place. If you want me to raise separate issues let me know.

**Comment by rhosking** [comment]
Superseded by #285
