### ISSUE TITLE
Problem generating new config.yaml file

### ISSUE THREAD

**Issue by bechandcock** [The-Academic-Observatory/observatory-platform#288]
I am having a problem creating the "config.yaml file" after the recent changes to the Observatory Platform. I thought it might have been a problem with my environment so I reinstalled everything and make sure I have all the latest updates from recent commits etc. I had thought I needed this file even if I don't want to run Airflow, so that I can set my JSON key etc. to access BigQuery. Prior to the recent change in the "config.yaml" file that is what I had been doing. However, after chatting with @aroelo it is sounding like this is not needed if I just need to use Report/Charing functionality and not use Airflow. If you could check this out though that would be great.

When I follow the new instructions from the README I get the following error (I am using Pycharm):

```
(venv) (base) Rebeccas-MBP:observatory-platform bec$ observatory generate config.yaml**

Traceback (most recent call last):
  File "/.../observatory-platform/venv/bin/observatory", line 6, in <module>
    from observatory_platform.cli.observatory import cli
  File "/.../observatory-platform/observatory_platform/cli/observatory.py", line 33, in <module>
    from observatory_platform.utils.config_utils import AirflowVar, \
  File "/.../observatory-platform/observatory_platform/utils/config_utils.py", line 27, in <module>
    import airflow
  File "/.../observatory-platform/venv/lib/python3.7/site-packages/airflow/__init__.py", line 43, in <module>
    from airflow.models import DAG
  File ".../observatory-platform/venv/lib/python3.7/site-packages/airflow/models/__init__.py", line 21, in <module>
    from airflow.models.baseoperator import BaseOperator, BaseOperatorLink  # noqa: F401
  File "/.../observatory-platform/venv/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 43, in <module>
    from airflow.models.dag import DAG
  File ".../observatory-platform/venv/lib/python3.7/site-packages/airflow/models/dag.py", line 47, in <module>
    from airflow.executors import LocalExecutor, get_default_executor
  File "/.../observatory-platform/venv/lib/python3.7/site-packages/airflow/executors/__init__.py", line 23, in <module>
    from airflow.executors.base_executor import BaseExecutor # noqa
  File "/.../observatory-platform/venv/lib/python3.7/site-packages/airflow/executors/base_executor.py", line 24, in <module>
    import airflow.utils.dag_processing
  File "/.../observatory-platform/venv/lib/python3.7/site-packages/airflow/utils/dag_processing.py", line 40, in <module>
    from setproctitle import setproctitle
ImportError: dlopen(/.../observatory-platform/venv/lib/python3.7/site-packages/setproctitle.cpython-37m-darwin.so, 2): Symbol not found: _Py_GetArgcArgv
  Referenced from: /.../observatory-platform/venv/lib/python3.7/site-packages/setproctitle.cpython-37m-darwin.so
  Expected in: flat namespace
 in /.../observatory-platform/venv/lib/python3.7/site-packages/setproctitle.cpython-37m-darwin.so
```

**Comment by bechandcock** [comment]
@jdddog the config.yaml file now generates OK, but when I try to run functions which access the observatory platform I now get the following error, which seems to be related also to the recent changes with airflow?

```
    from observatory_platform.utils.gc_utils import (run_bigquery_query)
  File ".../observatory-platform/observatory_platform/utils/gc_utils.py", line 29, in <module>
    import pendulum
ModuleNotFoundError: No module named 'pendulum'
```

**Comment by aroelo** [comment]
> @jdddog the config.yaml file now generates OK, but when I try to run functions which access the observatory platform I now get the following error, which seems to be related also to the recent changes with airflow?
> 
> ```
>     from observatory_platform.utils.gc_utils import (run_bigquery_query)
>   File ".../observatory-platform/observatory_platform/utils/gc_utils.py", line 29, in <module>
>     import pendulum
> ModuleNotFoundError: No module named 'pendulum'
> ```

How did you solve the `Symbol not found: _Py_GetArgcArgv` error? Just in case someone will have the same issue later.

Pendulum is installed with airflow, this is the 'apache-airflow==1.10.11' reference in the requirements.txt file. So it should be installed at the `pip3 install -e .` step.
I could have a look tomorrow if you'd like if you bring the laptop in? :-)

**Comment by bechandcock** [comment]
I did not do anything specific to fix the `'Symbol not found: _Py_GetArgcArgv'` error so I am assuming that of the recent changes the the OP seems to have fixed it as everything else I am doing is identical.

Yeah, I saw pendulum (and the next library after it) are part fo Airflow, which I am not using. I also tried installing them individually from within the virtual environment (which was successful) but then the library still could not find it to import. If I comment out those two libraries, the next set of new libraries fails too, which is why I thought this all connected to the rennet changes to the OP.

**Comment by bechandcock** [comment]
Thanks, having a look at it together on Tuesday would be great :-) 

PS with the recent changes to the Reporting library, now my old reports do not work either. I have installed and run these over a dozen times successfully up to about a week ago.

**Comment by bechandcock** [comment]
@aroelo and I worked through this today. The issue is around the creation of the virtual environment within the Pycharm GUI. We were not sure why, as I have been using Pycharm for my virtual environments for months, and if I roll back to a version of the OP from a couple of weeks OK things work OK.

The solution is to use the terminal within Pycharm to create the virtual environment, as per the instructions on the OP landing page. Code in seperate repositories to the OP is still not picking up the environment variable containing the path to the JSON credentials file, so that now needs to be hard coded in the code. This is OK for now as a work around as this is my test repository, but down the path this will need to made clear to users.

**Comment by aroelo** [comment]
It seems to be related to the 'base interpreter' that is used to create the virtual environment.

In this case it was defaulted to `/usr/bin/python3` for Pycharm, however as per the instructions on github of our repository the virtualenv is created based on python3.7 from brew and the path is along the lines of `/usr/local/opt/python@3.7`

A quick google search on the 'Py_GetArgcArgv' error shows that this is related to the python version. I'm not sure exactly which version does/does not work, as the comments show different versions that don't work.

For me, creating a virtualenv with python 3.8.2 from `/usr/bin/python3` gives an error similar to Rebecca's.
Creating a virtualenv with python 3.7.7 from brew works without issues.

For Rebecca I believe the virtualenv that does not work is based on python 3.7.2 from `/usr/bin/python3`.
And creating a virtualenv with python 3.7.8 from brew works without issues.

https://github.com/apache/airflow/issues/10961
https://github.com/dvarrazzo/py-setproctitle/issues/82
