### ISSUE TITLE
Data issues - general (PLACEHOLDER)

### ISSUE THREAD

**Issue by bechandcock** [The-Academic-Observatory/observatory-platform#318]
@cameronneylon suggested that we start a draft GitHub Issue to capture general data issues that come up. This Issue may be supplemented by one of other collection methods currently under discussion. 

This is linked to #285 #data and the Data Quality project.

**Data Issues List**
- [GRIDS] The issue is that there are times when MAG is making incorrect assignments of author affiliation GRIDs, sometimes consistently for an institution. This may be a known problem of institutions with missing GRIDs. One solution which was floated was the idea of adding new fields to the doi table as a supplement to the two sets of author affiliation fields there. These proposed fields would be for “COKI alternate” GRIDs for when the MAG one is missing or known to not be correct.

**Comment by cameronneylon** [comment]
Would be helpful for some exploratory work to include the cited/cited-by articles from MAG in the DOI table or otherwise have those in Elastic at some point. Use case is for building co-citation sets for articles and calculating more complex network metrics.

**Comment by rhosking** [comment]
This issue has been solved with the mag_affiliation_override table, which is working in production
