### ISSUE TITLE
Document 'description' fields in dataset schemas

### ISSUE THREAD

**Issue by jdddog** [The-Academic-Observatory/observatory-platform#332]
The following datasets need the "description" field added to their schemas:
* [ ] MAG
* [x] Crossref Metadata https://github.com/The-Academic-Observatory/observatory-platform/pull/338
* [ ] Fundref
* [x] Unpaywall https://github.com/The-Academic-Observatory/observatory-platform/pull/339
* [x] GRID https://github.com/The-Academic-Observatory/observatory-platform/pull/334

There are five datasets left to document, so it would be good if we each do one each @rhosking, @bechandcock, @aroelo, @tuanchien. Add a comment with the dataset that you will document, I will document the dataset that nobody picks.

P.S. the following datasets are already documented fully:
* Geonames
* Open Citations
* Scopus
* Web of Science

**Comment by rhosking** [comment]
I can do MAG, and the aggregated tables

**Comment by tuanchien** [comment]
I'll take GRID

**Comment by bechandcock** [comment]
Happy to do any of them (In January :-) )

**Comment by aroelo** [comment]
I'm happy to do Crossref Metadata

**Comment by aroelo** [comment]
I had a look at Unpaywall as well, might have a look at Fundref tomorrow depending on what other things there are to do. 

I thought this was the most sensible use of time, because I'm waiting on some comments on the telescope template and I know everyone else is busy with other things :-)

**Comment by bechandcock** [comment]
> I had a look at Unpaywall as well, might have a look at Fundref tomorrow depending on what other things there are to do.
> 
> I thought this was the most sensible use of time, because I'm waiting on some comments on the telescope template and I know everyone else is busy with other things :-)

Thanks @aroelo I won't get to these before the break, so anything extra you can get done is very helpful :-)
