### ISSUE TITLE
Schema changes and questions for the Dec-2020 schema revision

### ISSUE THREAD

**Issue by bechandcock** [The-Academic-Observatory/observatory-platform#343]
In December 2020 a new schema was developed for our BigQuery AO datasets. The first version of this was implemented in BigQuery and used to create Elasticsearch indexes in the new Kibana-Staging. This issue is to capture suggestions/revisions to the new schema.

**Comment by cameronneylon** [comment]
Reminder to self that there are a bunch of minor naming issues in the schema as it is appearing in various places. Consistency between gold_doaj and gold_just_doaj and in various places green_only appears where it should be percent_green_only. And there is an inconsistency between a few of the other names at different levels.

One thing that becomes clear from the API/Elastic work is that it would be good to have complete consistency across the subtables/subsets. There are a few places where that's not the case that I'll try to catch and collate here.

**Comment by cameronneylon** [comment]
In the ES schema for each subset the defining categorisation of the subset has a different name (eg the events subset is divided up by 'source', collaborations by 'collaborator_id'. This should probably have a consistent name, even if it is a copy to make the code consistent. Something like 'subset_category' that is used across all subsets to allow more reuse of code.

**Comment by cameronneylon** [comment]
Some issues in passing:

- [ ] in ES `green_only` should be `percent_green_only`
- [ ] inconsistency between the case of country codes for the aggregation-level ID and eg funder country codes
- [ ] outputs_without_citations is not being calculated correctly. Appears to be zero in most cases (which is clearly incorrect)

**Comment by aroelo** [comment]
-  published_year is formatted as date (YYYY-MM-DD), not related to schema naming, but typing. Can this be changed to a single integer for clarity?
- funder, group and publisher aggregations DO have country_code, but not country
- num_gold_doaj_outputs == num_gold_just_doaj_outputs?
- collaborations does not have 'total_outputs'

**Comment by rhosking** [comment]
closing as out of date (the API has changed a couple of times since these comments were made) and the task is superseded by a review of the whole API and ES schema.
