### ISSUE TITLE
Kibana iframe redirecting to login page everytime

### ISSUE THREAD

**Issue by alkimozaygen** [The-Academic-Observatory/observatory-platform#349]
When I try to log in on the iframe of the dashboard on the web page it redirects me to the login page. The only way to solve this is to use another browser (it didn't work with Safari, but works with Firefox).
There is a discussion on this at https://stackoverflow.com/questions/60772887/kibana-dashboard-embedded-in-iframe-redirecting-to-login-everytime-due-to-same

**Comment by rhosking** [comment]
No longer using iframes for embedding dashboards, so closing issue
