### ISSUE TITLE
New Github Org and repo setup for OAeBU project

### ISSUE THREAD

**Issue by rhosking** [The-Academic-Observatory/observatory-platform#351]
As the title implies, create an independant Github organisation and repo for hosting OAeBU specific telescopes and workflows. Using what we learn't from creating the separate academic-observatory repo

**Comment by bechandcock** [comment]
That would be great, thanks, as I have a note to consider moving the project/issues for OAeBU out of this repository too.

**Comment by rhosking** [comment]
new repo has now been created, this hosts all oaebu related workflows, schemas, mappings and documentation: https://github.com/The-Academic-Observatory/oaebu-workflows
