### ISSUE TITLE
Design Issues to address before moving Elasticsearch and Kibana into Production

### ISSUE THREAD

**Issue by rhosking** [The-Academic-Observatory/observatory-platform#368]
Status: Requirements gathering and scoping phase

Elasticsearch
- [ ] Do we want to put lifecycle policies in place to remove older indexes?
- [ ] Index mappings will change over time, how do we want to manage these changes, particularly breaking changes?
- [ ] For each dataset/index we manage, which of the following update polices make the most sense: 1) purely just append new records, 2) create a new index, and use index aliases to atomically change where queries are pointing, 3) update individual documents when upstream changes are detected
- [ ] For each data/index we manage, are the current index mappings appropriate? do we need to be indexing every field, and are any text analysers the most suitable choices? are any mappings incorrect.
- [ ] More broadly, for the use cases these indexes will support (search, APIs, Kibana dashboards) are the current data models fir for purpose? Are they efficient? Can we predict their impact of system resources over time?
- [ ] What will be the accepted process for rolling out updates (likely mappings or adding indexes, but sometimes more involved changes) across our various environments. During this process, what is being tested, what does a pass look like, and in what fashion are changes rolled out (including communication with the wider team)
- [ ] What monitoring and alerting should be put in place to proactively find issues in the running systems?
- [ ] Do we have an appropriate amount of testing in place for: The code that loads data into Elasticseach? common queries? scale? that our testing infrastructure around ES is working correctly?

Kibana
- [ ] Are we appropriately testing the Dashboards? Both initially, and ongoing checks to ensure they continue to function
- [ ] Are dashboards, index patterns, spaces and other settings appropriately backed up? should they all live in version control? if no, where?
- [ ] Can we actually turn this stored information into a functioning instance of ES/Kibana? both for spinning up testing instances, but also for disaster recovery and rolling out new features without too many manual steps
- [ ] Do we have sufficient documentation for the operations team to know what dashboards exist, what their SLAs are, who the points of contact are, and who is responsible for resolving various types of issue? Additionally, is this documentation sufficient for planning any major upgrades, mapping updates or other changes?
- [ ] Given the index mappings will change over time, are we prepared for managing the link between required dashboard updates and those index updates? What communications need to be in place? do we need a system that links dashboard versions with support index mapping versions? How are any changes to either dashboards or index mapping tested and verified?

**Comment by jdddog** [comment]
Elasticsearch
> - [ ] Do we want to put lifecycle policies in place to remove older indexes?

We definitely do for the DOIs table, we should only ever have two of these loaded at once. The other tables aren't too big to keep them all, at least for now.

> - [ ] Index mappings will change over time, how do we want to manage these changes, particularly breaking changes?

If you want to manage this well, then the aliases might need to be versioned. It will take more effort to implement this though.

> - [ ] For each dataset/index we manage, which of the following update polices make the most sense: 1) purely just append new records, 2) create a new index, and use index aliases to atomically change where queries are pointing, 3) update individual documents when upstream changes are detected

I think that for now we should just leave it as it is, i.e. number 2, it will take a lot more time to develop and test the other options at the moment.

> - [ ] For each data/index we manage, are the current index mappings appropriate? do we need to be indexing every field, and are any text analysers the most suitable choices? are any mappings incorrect.

I think that we should address this when we have a concrete use case that brings up this need.

> - [ ] More broadly, for the use cases these indexes will support (search, APIs, Kibana dashboards) are the current data models fir for purpose? Are they efficient? Can we predict their impact of system resources over time?

I think that we should address this when we have a concrete use case that brings up this need.

> - [ ] What will be the accepted process for rolling out updates (likely mappings or adding indexes, but sometimes more involved changes) across our various environments. During this process, what is being tested, what does a pass look like, and in what fashion are changes rolled out (including communication with the wider team)

We need an automated process, when the indexes are updated in the production instance, that copies them to the staging and develop instances (and deletes the existing indexes there). 

We need the same for the develop and staging BigQuery datasets.

> - [ ] What monitoring and alerting should be put in place to proactively find issues in the running systems?

Can we configure Elastic Monitoring for this somehow?

> - [ ] Are dashboards, index patterns, spaces and other settings appropriately backed up? should they all live in version control? if no, where?

The index patterns are already in version control. The dashboards and spaces should be in version control. 

> - [ ] Can we actually turn this stored information into a functioning instance of ES/Kibana? both for spinning up testing instances, but also for disaster recovery and rolling out new features without too many manual steps

I think that we should be able to do this. Ideally the dashboards developed in the develop instance could be committed to the repository and they would be automatically loaded into the staging and production instances.

**Comment by rhosking** [comment]
> If you want to manage this well, then the aliases might need to be versioned. It will take more effort to implement this though.

I'd like to get to this a point where it really stable, a big part of that is for me having a clear path/process for any updates going forward (without it requiring a big deep dive, scheduling exercise). So if it takes a little more work, then I think it worth it to get it right up front. So, I propose:
- Versioning the entire index-mapping/index-aliasing as a collective whole. Obviously we wouldn't want to update the aliases for each minor version update, so they can be have labels of only the major versions (aka no-breaking changes), while perhaps the underlying indexes could include minor versions?
- Dashboard and APIs will be versions according to whatever makes sense for each, but will maintain documentation (and backed by testing) to show what versions of the indexes they work correctly with


> I think that for now we should just leave it as it is, i.e. number 2, it will take a lot more time to develop and test the other options at the moment.

that sounds like a pragmatic choice. Enabling other methods for updating the indexes can be explicitly future work


> Can we configure Elastic Monitoring for this somehow?

I will look deeper into Elastic Monitoring. I think this should generally all we need, but with some explicit triggers for sending emails/slack notifications if there are system issues


> I think that we should be able to do this. Ideally the dashboards developed in the develop instance could be committed to the repository and they would be automatically loaded into the staging and production instances.

I think this makes sense, though with some thought as too when staging is updated. I'm not sure about automating every merged commit, however the pull-request/code review might already an appropriate process for getting things into the develop branch, and automatically deployed to staging? Or is that breaking the semantics, the develop branch deployed to staging? (I forget where we got with that discussion)

**Comment by rhosking** [comment]
The other thing to consider, is that we can automate the creation/deletion of as many elastic instances as we like. If they are short lived, they won't impact any budgets. When we take a deeper look into testing, there might be some value in exploring this

**Comment by rhosking** [comment]
@cameronneylon @bechandcock when you get a moment, can you take a look over this. It's currently focused at the infrastructural level, but I suspect items like 'defining a process for onboarding new indexes' might also be valuable inclusions.

Note, all of these requirements will likely be delivered in a couple of phases, just to de-risk each phase and allowing code to get out the door quicker. Work on development is looking to start around the end of this month, so there are still a few weeks to finish nailing down requirements.

**Comment by cameronneylon** [comment]
> Status: Requirements gathering and scoping phase
> 
> Elasticsearch
> 
>     * [ ]  Do we want to put lifecycle policies in place to remove older indexes?

Both for the API and the dashboards (in the future) there is value in being able to define specific states for future reproducibility. For reports/API it will be useful to record the specific ES state they were drawn from and then be able to reproduce that. If there was ultimately a hierachy of things that had a longer retention cycle (eg always use the January or July index for the final versions of reports that need to be reproducible because those ones will be retained for a longer period) then that would be fine. Ultimately we probably want to be sharing report level static data with outputs anyway.

>     * [ ]  Index mappings will change over time, how do we want to manage these changes, particularly breaking changes?

No strong views, but it would be good to have a contract on what is stable for which periods. Treating breaking changes and backwards compatibility through something similar to a standard versioning model seems ok to me.

>     * [ ]  For each dataset/index we manage, which of the following update polices make the most sense: 1) purely just append new records, 2) create a new index, and use index aliases to atomically change where queries are pointing, 3) update individual documents when upstream changes are detected

I have views on how we might do this with streaming changes for an object-level (DOI) index but for the others clean replace and version makes more sense to me.

>     * [ ]  For each data/index we manage, are the current index mappings appropriate? do we need to be indexing every field, and are any text analysers the most suitable choices? are any mappings incorrect.

Mostly they're good. There are additional data elements to add and some potential slight changes for mappings that would be helpful. Noting the current 'ignore-beyond' is set to 256 for some elements that have longer sets of keywords we should consider the implications of that I think.

>     * [ ]  More broadly, for the use cases these indexes will support (search, APIs, Kibana dashboards) are the current data models fir for purpose? Are they efficient? Can we predict their impact of system resources over time?

I have some suggested changes to make - what's the most efficient way of getting them on the table? I can prepare a pull request for some basic ones that are immediate results of the BTAA work but should we organise a proper workshop to work through some aspects of this?

> Kibana
> 
>     * [ ]  Are we appropriately testing the Dashboards? Both initially, and ongoing checks to ensure they continue to function

No. We need some form of automated testing, at least that things are still up and have some defined elements. I'm not sure of how best to do more detailed testing over time. A dependency map seems critical at this point.

>     * [ ]  Are dashboards, index patterns, spaces and other settings appropriately backed up? should they all live in version control? if no, where?

I'd like to see them in version control but don't claim any particular expertise on the right way to approach that.

>     * [ ]  Do we have sufficient documentation for the operations team to know what dashboards exist, what their SLAs are, who the points of contact are, and who is responsible for resolving various types of issue? Additionally, is this documentation sufficient for planning any major upgrades, mapping updates or other changes?

No, part of this is what I mean by the dependency map. This has to go both directions. What can I quickly spin up? How stable will that be? If I want stability > X how do I register that and the dependencies. To what extent could that be automated by inspecting the dashboard JSON? 

>     * [ ]  Given the index mappings will change over time, are we prepared for managing the link between required dashboard updates and those index updates? What communications need to be in place? do we need a system that links dashboard versions with support index mapping versions? How are any changes to either dashboards or index mapping tested and verified?

We are not currently prepared for this. We need a clear separation between index changes and dashboard changes, but there are real challenges if the number of dashboards starts to grow (particularly demonstration ones or tests that then get adoption). This will come up more and more often as we build a demo of something, and then we'll need to transition that to some sort of support arrangement (or not, if there isn't ongoing financial support to keep it maintained).

**Comment by rhosking** [comment]
outdated, most of these points have been implemented and the remainder is out of date or captured elsewhere
