### ISSUE TITLE
Create documentation for dataset: Web of Science

### ISSUE THREAD

**Issue by bechandcock** [The-Academic-Observatory/observatory-platform#42]
## Dataset: Web of Science
**BigQuery dataset name:** web_of_science
**BigQuery location:** `academic-observatory-telescope : web_of_science`
**Category:** e.g. raw/original data
**BigQuery key table(s):** e.g. wos_v1
**Dataset description:** e.g. Bibliographic and citation data

**Comment by rhosking** [comment]
added @tuanchien for follow up work once the telescope is complete

**Comment by tuanchien** [comment]
Is the documentation merged as part of the Wos Telescope adequate, or is there further documentation required somewhere?

**Comment by bechandcock** [comment]
> Is the documentation merged as part of the Wos Telescope adequate, or is there further documentation required somewhere?

For each dataset there is also the "Dataset" documentation, which links to the vendor version of the schema etc. This looks like it has been populated for WoS (I did not do this one), so maybe a final check to see if you are happy with that now that we have locked in the telescopes?

https://observatory-platform.readthedocs.io/en/latest/datasets/provider_wos/index.html

**Comment by tuanchien** [comment]
Implemented by #21 with a documentation update in #20
