### ISSUE TITLE
Install observatory platform packages on Windows

### ISSUE THREAD

**Issue by Rafiq-A-Mohammed** [The-Academic-Observatory/observatory-platform#458]
Currently there is no documentation to install the observatory platform on Windows.
We have tried to install the different packages using the following steps.

First, we installed python 3.7.9 using the Windows x86-64 executable installer from https://www.python.org/downloads/release/python-379/.

Then, we made a virtual env following the instructions here https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/

Installing pip and virtualenv
```
py -m pip install --upgrade pip
py -m pip install --user virtualenv
```

Then, we cloned the observatory-platform repository and created a virtualenv inside the observatory-platform directory.

Creating the virtualenv  and activating it
```
py -m venv venv
.\venv\Scripts\activate
```

Then, we successfully installed the observatory platform package with:
`pip3 install -e observatory-platform`

And tried to install the observatory reports package with:
`pip3 install -e observatory-reports`

However, this gave an error, see below:
```
(venv) C:\Users\281315B\Documents\GitHub\observatory-platform>pip3 install -e observatory-reports
Obtaining file:///C:/Users/281315B/Documents/GitHub/observatory-platform/observatory-reports
Collecting matplotlib==3.1.*
  Downloading matplotlib-3.1.3-cp37-cp37m-win_amd64.whl (9.1 MB)
     |████████████████████████████████| 9.1 MB 6.8 MB/s
Collecting pandas==1.2.*
  Downloading pandas-1.2.5-cp37-cp37m-win_amd64.whl (9.1 MB)
     |████████████████████████████████| 9.1 MB ...
Collecting seaborn==0.11.*
  Downloading seaborn-0.11.1-py3-none-any.whl (285 kB)
     |████████████████████████████████| 285 kB ...
Collecting geopandas==0.8.*
  Using cached geopandas-0.8.2-py2.py3-none-any.whl (962 kB)
Requirement already satisfied: numpy==1.19.* in c:\users\281315b\documents\github\observatory-platform\venv\lib\site-packages (from observatory-reports==2021.4.1.dev42) (1.19.5)
Collecting ipython==7.16.*
  Using cached ipython-7.16.1-py3-none-any.whl (785 kB)
Collecting pydata-google-auth==1.1.*
  Using cached pydata_google_auth-1.1.0-py2.py3-none-any.whl (13 kB)
Collecting num2words==0.5.*
  Using cached num2words-0.5.10-py3-none-any.whl (101 kB)
Requirement already satisfied: pandas-gbq==0.15.* in c:\users\281315b\documents\github\observatory-platform\venv\lib\site-packages (from observatory-reports==2021.4.1.dev42) (0.15.0)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.1-cp37-cp37m-win_amd64.whl (51 kB)
     |████████████████████████████████| 51 kB ...
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\281315b\documents\github\observatory-platform\venv\lib\site-packages (from matplotlib==3.1.*->observatory-reports==2021.4.1.dev42) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\281315b\documents\github\observatory-platform\venv\lib\site-packages (from matplotlib==3.1.*->observatory-reports==2021.4.1.dev42) (2.8.2)
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Requirement already satisfied: pytz>=2017.3 in c:\users\281315b\documents\github\observatory-platform\venv\lib\site-packages (from pandas==1.2.*->observatory-reports==2021.4.1.dev42) (2021.1)
Collecting scipy>=1.0
  Downloading scipy-1.7.0-cp37-cp37m-win_amd64.whl (33.6 MB)
     |████████████████████████████████| 33.6 MB 6.4 MB/s
Collecting shapely
  Downloading Shapely-1.7.1-cp37-cp37m-win_amd64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB ...
Collecting pyproj>=2.2.0
  Downloading pyproj-3.1.0-cp37-cp37m-win_amd64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB ...
Collecting fiona
  Using cached Fiona-1.8.20.tar.gz (1.3 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\281315b\documents\github\observatory-platform\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\281315B\\AppData\\Local\\Temp\\pip-install-uqpey2xj\\fiona\\setup.py'"'"'; __file__='"'"'C:\\Users\\281315B\\AppData\\Local\\Temp\\pip-install-uqpey2xj\\fiona\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\281315B\AppData\Local\Temp\pip-pip-egg-info-h0vacqol'
         cwd: C:\Users\281315B\AppData\Local\Temp\pip-install-uqpey2xj\fiona\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 21.2.1 is available.
You should consider upgrading via the 'c:\users\281315b\documents\github\observatory-platform\venv\scripts\python.exe -m pip install --upgrade pip' command.
```

Written by @aroelo :-)

**Comment by jdddog** [comment]
Hi @Rafiq-A-Mohammed, thanks for submitting the issue.

There is no documentation to install the Observatory Platform on Windows because it doesn't support Windows at the moment, from the [README](https://github.com/The-Academic-Observatory/observatory-platform#installation):

> Installation
> Observatory Platform supports Python 3.7 and above on Linux and MacOS.

If we want it to work on Windows, then we will need to allocate time for someone to scope if it is possible, in particular, what Python dependencies need to change and if there are any additional Windows system dependencies that are required.

For now, I would recommend using Ubuntu or Mac OS, unless you would like to work on scoping out what dependencies are causing the problems?

**Comment by aroelo** [comment]
Hi Jamie, thanks for having a look

> Aniek says that you need to use the `observatory-reports` package? You could try to just install the `observatory-reports` and not the other packages. We should ideally split `observatory-reports` into it's own Github project so that it is easier to work with, it would probably be easier to get that one package working on Windows as it has less dependencies.

The error that is mentioned in the issue is actually for installing `observatory-reports`, we were able to install `observatory-platform` successfully.

**Comment by rhosking** [comment]
@Rafiq-A-Mohammed @aroelo is it ok if this ticket is now closed? as Jamie said, there is no current plans to support windows but if that was something of interest create a separate issue for scoping out what that would look like we be the best next steps.

Also noting, with recent changes we are splitting out the observatory-reports into it's own project, which might help with some of the problems

**Comment by aroelo** [comment]
> @Rafiq-A-Mohammed @aroelo is it ok if this ticket is now closed? as Jamie said, there is no current plans to support windows but if that was something of interest, creating a separate issue for scoping out what that would look like we be the best next steps.
> 
> Also noting, with recent changes we are splitting out the observatory-reports into it's own project, which might help with some of the problems

Sounds good to me
