### ISSUE TITLE
Create documentation for dataset: Open Citations

### ISSUE THREAD

**Issue by bechandcock** [The-Academic-Observatory/observatory-platform#46]
## Dataset long name: Open Citations
**Dataset short name:** open_citations
**BigQuery location:** `academic-observatory-telescope : open_citations`
**Category:** e.g. raw/original data
**BigQuery key table(s):** e.g. open_citations_YYYY_MM_DD
**Dataset description:** e.g. Bibliographic and citation data

**Comment by rhosking** [comment]
added @tuanchien for follow up work once the telescope is complete

**Comment by bechandcock** [comment]
This has changed in what was originally envisioned for these datasets. It now refers to writing the dataset documentation under a Elsevier section in the Datasets section (as different from the Telescopes section).
https://observatory-platform.readthedocs.io/en/latest/datasets/index.html
