### ISSUE TITLE
Usage of pre-commit tool

### ISSUE THREAD

**Issue by aroelo** [The-Academic-Observatory/observatory-platform#465]
See https://docs.google.com/document/d/15XhGB74dN_FCBKOmc8aYWR-xGxsqqoXo8nX1vCwQnZ4/ for current workflow of integrating Jira and Github.

The need to mention Jira issue keys in your commit message led me to take a look at different git hooks that can be used before/during your commit.

There is a package [pre-commit](https://pre-commit.com/) that could be used to manage these hooks.
One option would be to add a pre-commit config file that can automatically prefix your commit message with a Jira issue key based on the branch name (see [example](https://github.com/The-Academic-Observatory/jira-integration-test/blob/INF-10/fix_something/.pre-commit-config.yaml)).
There are existing hooks that we could use to do this (https://github.com/avilaton/add-msg-issue-prefix-hook and https://github.com/radix-ai/auto-smart-commit) or add our own simple shell script (trying it out [here](https://github.com/The-Academic-Observatory/jira-integration-test/blob/INF-10/fix_something/prefix_commit_jira.sh))

There are also other existing hooks we could potentially use, for example checking if the files are formatted with 'black'.
A list of supported hooks can be found here: 
https://pre-commit.com/hooks.html

Alternatively we could add a file with this shell script to our repository, with instructions to move this file to `.git/hooks/prepare-commit-msg` if you would like to make use of the git hook.

@rhosking @jdddog @tuanchien Are there any thoughts on using pre-commit, and using other hooks besides the Jira one?

**Comment by tuanchien** [comment]
If we want to standardise the way we push things, I'm happy to use pre-commit hooks.
