### ISSUE TITLE
Create local directory in container corresponding with cloud composer directory

### ISSUE THREAD

**Issue by aroelo** [The-Academic-Observatory/observatory-platform#68]
As we shortly discussed through slack there is a '/home/airflow/gcs/data' directory on every node created by cloud composer that is synced with a storage bucket using gcs fuse. (https://cloud.google.com/composer/docs/concepts/cloud-storage)

I think it would be useful for local development if there is a directory in the webserver container with the same name.

Do you think it would be possible to implement this?

**Comment by jdddog** [comment]
Closing because https://github.com/The-Academic-Observatory/observatory-platform/pull/206 is merged.
