### ISSUE TITLE
Data Element Request: Add "Gold Only" to Open Access types

### ISSUE THREAD

**Issue by cameronneylon** [The-Academic-Observatory/observatory-platform#70]
**Name**: Add an Open Access type of "Gold Only"
**Subject Area**: Open Access
**Table**: DOIs table or Unpaywall processing workflow

A potential metric for the effectiveness of university infrastructures for open access is the proportion of those objects that are gold OA that are also in the repository. An initial proxy for this would be the count of those items that are "gold only". This is the inverse of an existing oa type called "green only".

Future development might be "count of gold that is also in home repo" but that would be dependent on resolving the residual issues with home repository representation.

**Comment by rhosking** [comment]
Superseded by #285
