### ISSUE TITLE
Telescope workflow implementation: Crossref events

### ISSUE THREAD

**Issue by aroelo** [The-Academic-Observatory/observatory-platform#78]
**Name**: Crossref events
**Subject Area**: Publication Events
**Harvest Type**: API 
**Query Type**: Pagination
**Snapshot Type**: N/A
**Snapshot Frequency**: N/A

See https://docs.google.com/spreadsheets/d/1ABHRxaGqjRq9j_oUftlSmhd2pBY09Pvc5n-JaleRbeI for more detailed info on data source.

**Comment by aroelo** [comment]
Some small questions:
* It is not necessary, but preferred that we give an email address when using the crossref events API (https://www.eventdata.crossref.org/guide/service/query-api/#tell-us-who-you-are). So far I've used my curtin one; aniek.roelofs@curtin.edu.au. Which email address would be best to use in our production environment?

* When trying to get the data I often get a 503 error that the server is unavailable. What is a reasonable amount of retries before marking a task as failed in airflow? It's now set at 3 and tasks still fail quite regularly.

**Comment by rhosking** [comment]
Your Curtin email address is fine for the moment, it is not super important. But I think once we move it into production, we should use a common email alias for things like this, that forwards emails to all of us (or the relevant sub group). I will take that on as a task to set something up.

Yeah, the 503 thing is interesting. This might be my lack of understanding of Airflow here, but is it possible to start exponentially backing off for each failure. Aka wait increasing longer amounts of time? The other thing, as we discussed, was there service was down for a few days. Is it possible for the task to just be retried at a later date? the backoff might achieve a similar result though

**Comment by aroelo** [comment]
The 'until-updated' parameter is now working, see https://gitlab.com/crossref/issues/-/issues/877. The telescope should be updated accordingly.
