### ISSUE TITLE
Create a 'How to Write A Telescope' Guide

### ISSUE THREAD

**Issue by rhosking** [The-Academic-Observatory/observatory-platform#84]
An opinionated flavour of the standard tutorials and guides for creating Airflow workflows, but catering towards the needs and context of the observatory platform.

I anticipate it to be as much of a hub for linking together all the best examples of best practice for Airflow more generally as it is about observatory specific practice. We don't want to diverge from the bulk on the community. Where we might need extra content is around the shared libraries we are creating for the types of data we are working with, alongside the continuing development of helper services that simply individual workflows

**Comment by rhosking** [comment]
@jdddog @aroelo @tuanchien it would be good if you can all get together to discuss what this might look like once the current round of development starts wrapping up. With @jdddog proposed changes to the repositories, it makes sense to write this up once the dust settles

**Comment by jdddog** [comment]
We can add @aroelo's suggestion here to the list: https://github.com/The-Academic-Observatory/observatory-platform/issues/225

**Comment by aroelo** [comment]
Perhaps it would be nice to add a description that's visible in the UI for the tasks/DAG, see: https://airflow.apache.org/docs/stable/concepts.html#documentation-notes

**Comment by jdddog** [comment]
> Perhaps it would be nice to add a description that's visible in the UI for the tasks/DAG, see: https://airflow.apache.org/docs/stable/concepts.html#documentation-notes

That would be great!

**Comment by aroelo** [comment]
To better monitor the status of the DAGs, we could add an 'on_failure_callback' function to each DAG that will send a slack notification to the airflow channel (only in prod/staging?).

**Comment by tuanchien** [comment]
It seems like there is a lot of duplicated work between telescopes.  For example, the airflow messaging, bq load, and cleanup.  Maybe we should implement template pipelines for most common patterns, and when people decide to use that, only get them to implement certain specialised things.

For example, download and transform might be the most commonly changed components, so if a simple telescope template got them to implement a download function that fetches, saves, and returns a list of files saved,  and a transform function that converts that into a json ready format, then you can save them from doing all the messaging and json conversion stuff.

**Comment by tuanchien** [comment]
The concept of a Telescope needs to be more explicit.  Is it just anything that's not in the dag definition, responsible for all airflow and non airflow interactions, or should it be airflow specific interactions, with non airflow functionality offloaded to other functions classes.  Right now there seems to be a mixture where in some telescopes there is a mostly clean separation, with heavy lifting done in non telescope class methods in some cases, and a mix in other cases.

**Comment by tuanchien** [comment]
Would be good to figure out a way to automate the process of generating a new schema from a data source, perhaps in a script that pushes new data to bq in auto detect schema mode, then auto extracts the schema.

**Comment by tuanchien** [comment]
Perhaps to more easily facilitate data analysis later, perhaps we should come up with guidelines for the naming and structure of recorded fields.  This has a trade off.

Pros
- SQL queries can be simplified if pulling from different datasets/tables because field names will be common (when they exist) between different datasets.
- Can use a single schema

Cons
- Might require additional parsing code for each telescope since it's likely each source is doing things differently.
- The definition and level of detail for a given field might vary between sources so it would require a fair bit of care to design the guidelines for exactly what goes into each field.
- Schemas might be overly big
