### ISSUE TITLE
REPORTS: Write the 'How to create a Report' Documentation

### ISSUE THREAD

**Issue by rhosking** [The-Academic-Observatory/observatory-platform#96]
This is end-user documentation to make it as straight-forward as possible for creating a new report. This task is for an initial design for a first prototype. This documentation will grow over time in step with future development

**Comment by bechandcock** [comment]
This tasks has been partially done as part of Phase 1. I have documenting the process of running the reporting library with the new setup to create new reports. 

~ Reporting Project Directory > AutoReports_3_TechNotes

What is not documented is creating new custom reports with a generic demo template, so I will leave this open.
