### ISSUE TITLE
Review reporting codebase for GCP specific functionality, consider moving this to utility libraries to ensure platform independence

### ISSUE THREAD

**Issue by rhosking** [The-Academic-Observatory/observatory-platform#99]
Code targeting specific cloud providers or otherwise should ideally be abstracted away to specific utility libraries. This is not always possible, but serves as an ideal.

I noticed a few references throughout the various files that could be targets for creating utility classes in the main /utils folder, and importing that code in. This may aid our work later when integrating this codebase into airflow workflows

**Comment by bechandcock** [comment]
Note: closed as this issue was superseded by the changes to how we implemented the reporting library.
